[build]
publish = "dist/"
command = "yarn build"

[[redirects]]
  from = "/graphql/*"
  to = "https://links-api.avosapps.us/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/graphql/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
